# Generated by Django 5.2.4 on 2025-08-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('vendor', models.CharField(max_length=255, verbose_name='Store / Vendor')),
                ('exclude', models.BooleanField(default=False, verbose_name='Escludi Spesa Da analysts')),
                ('indispensable', models.BooleanField(default=False, verbose_name='Spesa indispensabile')),
                ('avoidable', models.BooleanField(default=False, verbose_name='Spesa evitabile')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='$ Amount')),
                ('category', models.CharField(max_length=100, verbose_name='Expense Category')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='SubCategory')),
                ('notes', models.TextField(blank=True, verbose_name='Notes (Optional)')),
            ],
        ),
    ]
